apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: "geodataloader-srv"
  name: "geodataloader-srv"
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: geo-data-loader
status:
  loadBalancer: {}
